#!/bin/sh

unset SESSION_MANAGER

xrdb $HOME/.Xresources
xsetroot -solid grey
x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
x-window-manager &

urxvt &

# exec awesome

# sxhkd &
# exec bspwm


# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1
unset DBUS_SESSION_BUS_ADDRESS
gnome-panel &
gnome-settings-daemon &
metacity &
nautilus &
gnome-terminal &
. /etc/X11/Xsession
gnome-session &
# /etc/X11/Xsession
