directory: /home/eric/petrie/beets
library: /home/eric/petrie/beets/musiclibrary.blb

ui:
    color: yes
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: red
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue

import:
    copy: no
    move: no
    link: yes
    write: no
    
plex:
    host: localhost
    port: 32400
    token: 
